services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

  django_app:
    build: ./server
    container_name: django_docker
    ports:
      - "4433:4433"
      - "8000:8000"
    depends_on:
      - db
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DEBUG: ${DEBUG}
      DJANGO_LOGLEVEL: ${DJANGO_LOGLEVEL}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
    env_file:
      - .env
    volumes:
      - ./certs:/app/certs
      - ./to_send:/app/dossier_partage

  client1:
    image: client
    build: ./client
    depends_on:
      - django_app
    environment:
      NAME: "client1"
      VT_API_KEY: ${AGENT_VT_API_KEY}
      ABUSEIPDB_API_KEY: ${AGENT_ABUSEIPDB_API_KEY}
    env_file:
      - .env
    volumes:
      - ./client1:/app/dossier_local
      - ./certs:/app/certs
    profiles:
      - agents

  client2:
    image: client
    depends_on:
      - django_app
    environment:
      NAME: "client2"
    volumes:
      - ./client2:/app/dossier_local
      - ./certs:/app/certs
    profiles:
      - agents

volumes:
  postgres_data:
