# Generated by Django 5.1.4 on 2025-04-07 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='adresse',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
    ]
