# Generated by Django 5.1.6 on 2025-04-18 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_agent_adresse'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to='certificates/'),
        ),
        migrations.AddField(
            model_name='agent',
            name='common_name',
            field=models.CharField(default='default', max_length=60),
            preserve_default=False,
        ),
    ]
