# Generated by Django 5.1.6 on 2025-04-19 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_agent_certificate_agent_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='type',
            field=models.CharField(max_length=100),
        ),
    ]