# Generated by Django 5.1.6 on 2025-02-17 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('add_date', models.DateTimeField(auto_now_add=True)),
                ('system', models.CharField(max_length=50)),
                ('down', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('source', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('pcap', models.FileField(blank=True, null=True, upload_to='static/alerts/%y/%m/%d')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.agent')),
            ],
        ),
    ]
