# Generated by Django 5.1.6 on 2025-03-24 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='agent',
        ),
        migrations.DeleteModel(
            name='LogNbRequest',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
        migrations.DeleteModel(
            name='Alert',
        ),
    ]
